version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: test_postgres
    environment:
      POSTGRES_USER: habib
      POSTGRES_PASSWORD: ilovecheese
      POSTGRES_DB: bistra_db
    networks:
      net:
        ipv4_address: 193.168.1.40
      
  backend:
    build: 
      context: ./backend
    container_name: backend
    networks:
      net:
        ipv4_address: 193.168.1.40
  
  frontend:
    build:
      context: ./frontend
    networks:
      net:
        ipv4_address: 193.168.1.40

  nginx:
      image: nginx:1.25
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./ssl:/etc/nginx/ssl
        - ./nginx/runtime_logs:/var/log/nginx
      networks:
        net:
          ipv4_address: 193.168.1.10
      depends_on:
        - frontend
        - backend
        - postgres

networks:
  net:
    ipam:
      config:
        - subnet: 193.168.1.0/24
