version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reactphpnetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - frontend
      - backend
      - postgres

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    networks:
      - reactphpnetwork
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    networks:
      - reactphpnetwork
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bistra_db
      POSTGRES_USER: habib
      POSTGRES_PASSWORD: ilovecheese
    networks:
      - reactphpnetwork

networks:
  reactphpnetwork:
